**Introdução ao Numpy**

In [9]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(matriz)

**Tipos**

In [19]:
matriz.dtype.name

'int32'

**Dimensões do DataFrame**

In [20]:
matriz.shape

(2, 3)

**Criando valores(passo a passo, espaçados ou randômicos)**

In [22]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [25]:
np.random.randint(0,30,5)

array([26, 18, 18, 10, 25])

In [32]:
matriz2 = np.random.randint(0,30,6).reshape(3,2)
matriz2

array([[ 9,  3],
       [ 8, 19],
       [ 7, 20]])

**Operações com Numpy**

In [36]:
matriz.max()

6

In [38]:
matriz.argmax()

5

In [46]:
matriz.mean()

3.5

In [40]:
matriz.std()

1.707825127659933

In [41]:
matriz3 = np.array([[2,4,6],[7,8,1]])
matriz3

array([[2, 4, 6],
       [7, 8, 1]])

In [42]:
matriz3.shape

(2, 3)

In [43]:
matriz + matriz3

array([[ 3,  6,  9],
       [11, 13,  7]])

In [44]:
matriz * matriz3

array([[ 2,  8, 18],
       [28, 40,  6]])

In [45]:
matriz3 ** 2

array([[ 4, 16, 36],
       [49, 64,  1]])

**Seleção e Alteração de valores**